excludes:
  paths:
    - pattern: "gradle/**"
      reason: "BUILD_TOOL_OF"
      comment: "This directory contains build tool gradle."
    - pattern: "gradle.bat/"
      reason: "BUILD_TOOL_OF"
      comment: "Gradle build tool (windows)."
    - pattern: "gradlew"
      reason: "BUILD_TOOL_OF"
      comment: "Gradle build tool (unix)."
    - pattern: ".git/**"
      reason: "OTHER"
      comment: "Exclude it."
    - pattern: "backend-spring-boot/**"
      reason: "OTHER"
      comment: "Exclude it."
    - pattern: "frontend-angular16/**"
      reason: "OTHER"
      comment: "Exclude it."
