excludes:
  scopes:
    - pattern: "devDependencies"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."
  paths:
    - pattern: "gradle/"
      reason: "BUILD_TOOL_OF"
      comment: "This directory contains build tool gradle."
    - pattern: "gradle/**"
      reason: "BUILD_TOOL_OF"
      comment: "This directory contains build tool gradle."
    - pattern: "gradle.bat/"
      reason: "BUILD_TOOL_OF"
      comment: "Gradle build tool (windows)."
    - pattern: "gradlew"
      reason: "BUILD_TOOL_OF"
      comment: "Gradle build tool (unix)."
    - pattern: ".git/"
      reason: "OTHER"
      comment: "Exclude it."
    - pattern: ".git/**"
      reason: "OTHER"
      comment: "Exclude it."
    - pattern: "backend-spring-boot/"
      reason: "OTHER"
      comment: "Exclude it."
    - pattern: "backend-spring-boot/**"
      reason: "OTHER"
      comment: "Exclude it."
    - pattern: "python-tools/"
      reason: "OTHER"
      comment: "Exclude it."
    - pattern: "python-tools/**"
      reason: "OTHER"
      comment: "Exclude it."
